const TABLE_SESSION_TTL_SECONDS =
  Number(process.env.TABLE_SESSION_TTL_SECONDS) || 30 * 60;
const TABLE_SESSION_HEARTBEAT_TTL_SECONDS =
  Number(process.env.TABLE_SESSION_HEARTBEAT_TTL_SECONDS) ||
  TABLE_SESSION_TTL_SECONDS;

module.exports = {
  TABLE_SESSION_TTL_SECONDS,
  TABLE_SESSION_HEARTBEAT_TTL_SECONDS,
};
